# Generated by Django 4.2.16 on 2024-10-03 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning_logs", "0002_entry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entry",
            old_name="added_date",
            new_name="date_added",
        ),
    ]
