# Generated by Django 4.2.16 on 2024-10-25 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning_logs", "0003_rename_added_date_entry_date_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="entry",
            name="text",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="topic",
            name="text",
            field=models.CharField(max_length=50),
        ),
    ]
